namespace fly.llvm

public sqrt(const double x, double out)
public sin(const double x, double out)
public cos(const double x, double out)
public fabs(const double x, double out)
public floor(const double x, double out)
public ceil(const double x, double out)
public round(const double x, double out)
public trunc(const double x, double out)
public exp(const double x, double out)
public exp2(const double x, double out)
public log(const double x, double out)
public log2(const double x, double out)
public log10(const double x, double out)
public tan(const double x, double out)
public pow(const double b, const double e, double out)
public fma(const double a, const double b, const double c, double out)
public fmin(const double a, const double b, double out)
public fmax(const double a, const double b, double out)
public copysign(const double x, const double y, double out)
public sqrtf(const float x, float out)
public fabsf(const float x, float out)
public floorf(const float x, float out)
public ceilf(const float x, float out)
public ctpop(const long n, int out)
public ctlz(const long n, int out)
public cttz(const long n, int out)
public bswap(const long n, long out)
public bitreverse(const long n, long out)

public memcpy(const pointer dst, const pointer src, const ulong n)
public memmove(const pointer dst, const pointer src, const ulong n)
public memset(const pointer dst, const byte val, const ulong n)

public strSize(const string s, int out)
public strByteAt(const string s, const int i, byte out)
public strGetPtr(const string s, pointer out)
public strMake(const pointer ptr, const int size, string out)
public strPoke(const pointer ptr, const int i, const byte val)
public ptrByteAt(const pointer ptr, const int i, byte out)
public longToInt(const long v, int out)
public ulongToLong(const ulong v, long out)
public ptrPokeLong(const pointer ptr, const int i, const long val)
public ptrPokeInt(const pointer ptr, const int i, const int val)
public ptrReadByte(const pointer ptr, const int i, byte out)
public ptrReadShort(const pointer ptr, const int i, short out)
public ptrReadInt(const pointer ptr, const int i, int out)
public ptrReadLong(const pointer ptr, const int i, long out)
public ptrPokeByte(const pointer ptr, const int i, const byte val)
public ptrPokeShort(const pointer ptr, const int i, const short val)
public memcmp(const pointer a, const pointer b, const ulong n, int out)

// Generic typed-slot intrinsics: element type T inferred per monomorphization.
// slotPokeT deep-clones owned values (string) on store; slotReadT returns a fresh
// clone of owned values; slotFreeT releases an owned-value element (no-op for
// trivial/handle types). Enables generic containers over any T.
public slotPokeT<T>(const pointer buf, const int byteOff, const T val)
public slotReadT<T>(const pointer buf, const int byteOff, T out)
public slotSizeT<T>(const T sample, int out)
public slotFreeT<T>(const pointer buf, const int byteOff, const T sample)
public slotHashT<T>(const T key, int out)
// 3-way compare of the element stored at buf+byteOff against key (no clone):
// <0, 0, >0. string → lexicographic (memcmp + length); integer → signed; ref → address.
public slotCmpT<T>(const pointer buf, const int byteOff, const T key, int out)
// Hash the element stored at buf+byteOff (no clone). sample carries the type T.
public slotHashAtT<T>(const pointer buf, const int byteOff, const T sample, int out)
