namespace fly.runtime

public mem_alloc(const ulong size, pointer out)
public mem_free(const pointer ptr, const ulong size)
public mem_realloc(const pointer ptr, const ulong newSize, pointer out)

public io_write(const int fd, const pointer buf, const ulong count, long out)

public proc_exit(const int code)
public proc_exec(const pointer path, const pointer argv, int out)

public thread_spawn(const pointer fn, const pointer arg, const ulong stackSize, int out)
public futex_wait(const pointer addr, const int expected)
public futex_wake(const pointer addr, const int count, int out)

public atomic_load_i32(const pointer addr, int out)
public atomic_store_i32(const pointer addr, const int val)
public atomic_cas_i32(const pointer addr, const int expected, const int desired, int out)
public atomic_fetch_add_i32(const pointer addr, const int delta, int out)

public erf(const double x, double out)
public tgamma(const double x, double out)
public asin(const double x, double out)
public acos(const double x, double out)
public atan(const double x, double out)
public atan2(const double y, const double x, double out)
public sinh(const double x, double out)
public cosh(const double x, double out)
public tanh(const double x, double out)
public hypot(const double x, const double y, double out)
public asinh(const double x, double out)
public acosh(const double x, double out)
public atanh(const double x, double out)
public erfc(const double x, double out)

public fs_open(const pointer path, const int flags, const int mode, int out)
public fs_close(const int fd)
public fs_read(const int fd, const pointer buf, const ulong count, long out)
public fs_write(const int fd, const pointer buf, const ulong count, long out)
public fs_seek(const int fd, const long offset, const int whence, long out)
public fs_stat(const pointer path, ulong size_out, int mode_out, int out)
public fs_lstat(const pointer path, ulong size_out, int mode_out, int out)
public fs_size(const pointer path, long out)
public fs_mode(const pointer path, int out)
public fs_lsize(const pointer path, long out)
public fs_lmode(const pointer path, int out)
public fs_mkdir(const pointer path, const int mode, int out)
public fs_rmdir(const pointer path, int out)
public fs_unlink(const pointer path, int out)
public fs_rename(const pointer src, const pointer dst, int out)
public fs_fsync(const int fd, int out)
public fs_truncate(const pointer path, const long size, int out)
public fs_chmod(const pointer path, const int mode, int out)
public fs_symlink(const pointer target, const pointer link, int out)
public fs_readlink(const pointer path, const pointer buf, const ulong size, int out)
public fs_getdents(const int fd, const pointer buf, const ulong size, int out)

public time_realtime(long sec_out, long nsec_out, int out)
public time_monotonic(long sec_out, long nsec_out, int out)
public time_now_ns(long out)
public time_mono_ns(long out)
public time_sleep(const long sec, const long nsec)

public env_getcwd(const pointer buf, const ulong cap, int out)
public env_chdir(const pointer path, int out)
public env_get(const pointer key, const pointer buf, const ulong size, int out)
public env_set(const pointer key, const pointer val, int out)
public env_delete(const pointer key, int out)
public env_all_count(int out)
public env_all_get(const int idx, const pointer key_buf, const ulong key_size, const pointer val_buf, const ulong val_size)
public env_hostname(const pointer buf, const ulong size, int out)
public env_args_count(int out)
public env_args_get(const int idx, const pointer buf, const ulong size, int out)

public str_slot_set(const pointer arr_base, const int idx, const pointer ptr, const int size)
public str_slot_get(const pointer arr_base, const int idx, long ptr_out, int size_out)
public str_slot_ptr(const pointer arr_base, const int idx, pointer out)
public str_slot_size(const pointer arr_base, const int idx, int out)
public env_args_fill(const pointer arr_base, const int count)
public env_all_fill(const pointer arr_base, const int count)
public env_osname(const pointer buf, const ulong size, int out)
public env_arch(const pointer buf, const ulong size, int out)
public env_kernel(const pointer buf, const ulong size, int out)
public env_kernelversion(const pointer buf, const ulong size, int out)
public env_exe_path(const pointer buf, const ulong size, int out)
