namespace fly.runtime


public void malloc(const ulong size, pointer out)
public void free(const pointer ptr)
public void realloc(const pointer ptr, const ulong size, pointer out)
public void _open(const pointer path, const int oflag, const int pmode, int out)
public void _close(const int fd, int out)
public void _read(const int fd, const pointer buf, const int count, int out)
public void _write(const int fd, const pointer buf, const int count, int out)
public void _lseeki64(const int fd, const long offset, const int origin, long out)
public void _setmode(const int fd, const int mode, int out)
public void GetStdHandle(const int nStdHandle, pointer out)
public void WriteFile(const pointer h, const pointer buf, const int n, const pointer written, const pointer overlapped, int out)
public void ExitProcess(const int code)
public void CreateThread(const pointer attrs, const ulong stack, const pointer start, const pointer param, const int flags, const pointer threadId, pointer out)
public void CloseHandle(const pointer h, int out)
public void CreateProcessA(const pointer app, const pointer cmd, const pointer pa, const pointer ta, const int inherit, const int flags, const pointer env, const pointer cwd, const pointer si, const pointer pi, int out)
public void GetLastError(int out)
public void WaitForSingleObject(const pointer h, const int ms, int out)
public void GetExitCodeProcess(const pointer h, const pointer code, int out)
public void WaitOnAddress(const pointer addr, const pointer compare, const ulong size, const int ms, int out)
public void WakeByAddressSingle(const pointer addr)
public void WakeByAddressAll(const pointer addr)
public void WSAStartup(const int version, const pointer data, int out)
public void socket(const int af, const int type, const int proto, long out)
public void bind(const long s, const pointer addr, const int len, int out)
public void listen(const long s, const int backlog, int out)
public void accept(const long s, const pointer addr, const pointer len, long out)
public void connect(const long s, const pointer addr, const int len, int out)
public void send(const long s, const pointer buf, const int n, const int flags, int out)
public void recv(const long s, const pointer buf, const int n, const int flags, int out)
public void sendto(const long s, const pointer buf, const int n, const int flags, const pointer addr, const int alen, int out)
public void recvfrom(const long s, const pointer buf, const int n, const int flags, const pointer addr, const pointer alen, int out)
public void shutdown(const long s, const int how, int out)
public void setsockopt(const long s, const int level, const int opt, const pointer val, const int len, int out)
public void getsockopt(const long s, const int level, const int opt, const pointer val, const pointer len, int out)
public void getsockname(const long s, const pointer addr, const pointer len, int out)
public void getpeername(const long s, const pointer addr, const pointer len, int out)
public void gethostbyname(const pointer name, pointer out)
public void gethostbyaddr(const pointer addr, const int len, const int type, pointer out)
public void closesocket(const long s, int out)
public void ioctlsocket(const long s, const int cmd, const pointer argp, int out)
public void WSAPoll(const pointer fds, const int nfds, const int timeout, int out)
public void WinHttpOpen(const pointer agentW, const int accessType, const pointer proxyW, const pointer bypassW, const int flags, pointer out)
public void WinHttpConnect(const pointer session, const pointer serverW, const int port, const int reserved, pointer out)
public void WinHttpOpenRequest(const pointer connect, const pointer verbW, const pointer objectW, const pointer versionW, const pointer referrerW, const pointer acceptTypes, const int flags, pointer out)
public void WinHttpSendRequest(const pointer request, const pointer headersW, const int headersLen, const pointer optional, const int optionalLen, const int totalLen, const long context, int out)
public void WinHttpReceiveResponse(const pointer request, const pointer reserved, int out)
public void WinHttpQueryHeaders(const pointer request, const int infoLevel, const pointer nameW, const pointer buffer, const pointer bufferLen, const pointer index, int out)
public void WinHttpReadData(const pointer request, const pointer buffer, const int toRead, const pointer readOut, int out)
public void WinHttpCloseHandle(const pointer h, int out)
public void __atomic_load_4(const pointer ptr, const int memorder, int out)
public void __atomic_store_4(const pointer ptr, const int val, const int memorder)
public void __atomic_compare_exchange_4(const pointer ptr, const pointer expected, const int desired, const int wk, const int success, const int failure, bool out)
public void __atomic_fetch_add_4(const pointer ptr, const int val, const int memorder, int out)
public void GetFileAttributesExA(const pointer path, const int level, const pointer info, int out)
public void FindFirstFileA(const pointer path, const pointer data, pointer out)
public void FindNextFileA(const pointer h, const pointer data, int out)
public void FindClose(const pointer h, int out)
public void CreateDirectoryA(const pointer path, const pointer sa, int out)
public void RemoveDirectoryA(const pointer path, int out)
public void DeleteFileA(const pointer path, int out)
public void MoveFileExA(const pointer src, const pointer dst, const int flags, int out)
public void CreateSymbolicLinkA(const pointer link, const pointer target, const int flags, int out)
public void CreateFileA(const pointer path, const int access, const int share, const pointer sa, const int disp, const int attrs, const pointer templ, pointer out)
public void SetFilePointerEx(const pointer h, const long dist, const pointer newp, const int method, int out)
public void SetEndOfFile(const pointer h, int out)
public void SetFileAttributesA(const pointer path, const int attrs, int out)
public void GetSystemTimeAsFileTime(const pointer ft)
public void QueryPerformanceCounter(const pointer cnt, int out)
public void QueryPerformanceFrequency(const pointer freq, int out)
public void Sleep(const int ms)
public void GetCurrentDirectoryA(const int n, const pointer buf, int out)
public void SetCurrentDirectoryA(const pointer path, int out)
public void GetEnvironmentVariableA(const pointer name, const pointer buf, const int n, int out)
public void SetEnvironmentVariableA(const pointer name, const pointer val, int out)
public void GetEnvironmentStringsA(pointer out)
public void FreeEnvironmentStringsA(const pointer block, int out)
public void GetComputerNameA(const pointer buf, const pointer size, int out)
public void GetVersion(int out)
public void RtlGetVersion(const pointer info, int out)
public void GetModuleFileNameA(const pointer mod, const pointer buf, const int n, int out)
public void GetCommandLineA(pointer out)
public void strlen(const pointer s, ulong out)
public void erf(const double x, double out)
public void erfc(const double x, double out)
public void tgamma(const double x, double out)
public void asin(const double x, double out)
public void acos(const double x, double out)
public void atan(const double x, double out)
public void atan2(const double y, const double x, double out)
public void sinh(const double x, double out)
public void cosh(const double x, double out)
public void tanh(const double x, double out)
public void hypot(const double x, const double y, double out)
public void asinh(const double x, double out)
public void acosh(const double x, double out)
public void atanh(const double x, double out)
public void mem_alloc(const ulong size, pointer out)
public void mem_free(const pointer ptr, const ulong size)
public void mem_realloc(const pointer ptr, const ulong newSize, pointer out)
public void io_write(const int fd, const pointer buf, const ulong count, long out)
public void proc_exit(const int code)
public void fs_open(const pointer path, const int flags, const int mode, int out)
public void fs_close(const int fd)
public void fs_read(const int fd, const pointer buf, const ulong count, long out)
public void fs_write(const int fd, const pointer buf, const ulong count, long out)
public void fs_seek(const int fd, const long offset, const int whence, long out)
public void io_set_binary(const int fd, int out)
public void fs_size(const pointer path, long out)
public void fs_mode(const pointer path, int out)
public void fs_lsize(const pointer path, long out)
public void fs_lmode(const pointer path, int out)
public void fs_mtime(const pointer path, long out)
public void fs_lmtime(const pointer path, long out)
public void fs_mkdir(const pointer path, const int mode, int out)
public void fs_rmdir(const pointer path, int out)
public void fs_unlink(const pointer path, int out)
public void fs_rename(const pointer src, const pointer dst, int out)
public void fs_fsync(const int fd, int out)
public void fs_truncate(const pointer path, const long size, int out)
public void fs_chmod(const pointer path, const int mode, int out)
public void fs_symlink(const pointer target, const pointer link, int out)
public void fs_readlink(const pointer path, const pointer buf, const ulong size, int out)
public void fs_getdents(const int fd, const pointer buf, const ulong size, int out)
public void dir_open(const pointer path, pointer out)
public void dir_read(const pointer ctx, const pointer buf, const ulong size, int out)
public void dir_close(const pointer ctx)
public void time_now_ns(long out)
public void time_mono_ns(long out)
public void time_sleep(const long sec, const long nsec)
public void env_chdir(const pointer path, int out)
public void env_set(const pointer key, const pointer val, int out)
public void env_delete(const pointer key, int out)
public void env_getcwd(const pointer buf, const ulong cap, int out)
public void env_get(const pointer key, const pointer buf, const ulong size, int out)
public void env_hostname(const pointer buf, const ulong size, int out)
public void env_arch(const pointer buf, const ulong size, int out)
public void env_kernel(const pointer buf, const ulong size, int out)
public void env_kernelversion(const pointer buf, const ulong size, int out)
public void env_osname(const pointer buf, const ulong size, int out)
public void env_exe_path(const pointer buf, const ulong size, int out)
public void env_all_count(int out)
public void env_all_fill(const pointer arr_base, const int count)
public void env_args_count(int out)
public void env_args_fill(const pointer arr_base, const int count)
public void env_init(const int argc, const pointer argv)
public void proc_exec(const pointer path, const pointer argv, int out)
public void proc_exec_redirect(const pointer path, const pointer argv, const pointer outPath, int out)
public void thread_spawn(const pointer fn, const pointer arg, const ulong stackSize, int out)
public void futex_wait(const pointer addr, const int expected)
public void futex_wake(const pointer addr, const int count, int out)
public void atomic_load_i32(const pointer addr, int out)
public void atomic_store_i32(const pointer addr, const int val)
public void atomic_cas_i32(const pointer addr, const int expected, const int desired, int out)
public void atomic_fetch_add_i32(const pointer addr, const int delta, int out)
public void net_init(int out)
public void net_socket(long out)
public void net_close(const long s)
public void net_shutdown(const long s, const int how, int out)
public void net_reuseaddr(const long s, int out)
public void net_set_nodelay(const long s, const int on, int out)
public void net_set_keepalive(const long s, const int on, int out)
public void net_set_broadcast(const long s, const int on, int out)
public void net_set_recvbuf(const long s, const int bytes, int out)
public void net_set_sendbuf(const long s, const int bytes, int out)
public void net_set_recv_timeout(const long s, const int ms, int out)
public void net_set_send_timeout(const long s, const int ms, int out)
public void net_set_linger(const long s, const int on, const int sec, int out)
public void net_set_nonblocking(const long s, const int on, int out)
public void net_sock_error(const long s, int out)
public void net_bind(const long s, const int addr, const int port, int out)
public void net_listen(const long s, const int backlog, int out)
public void net_accept(const long s, long out)
public void net_connect(const long s, const int addr, const int port, int out)
public void net_send(const long s, const pointer buf, const int n, long out)
public void net_recv(const long s, const pointer buf, const int n, long out)
public void net_local_port(const long s, int out)
public void net_socket_udp(long out)
public void net_send_to(const long s, const pointer buf, const int n, const int addr, const int port, long out)
public void net_recv_from(const long s, const pointer buf, const int n, const pointer from, long out)
public void net_https_available(int out)
public void net_https_request(const pointer verb, const pointer host, const int port, const pointer path, const pointer headers, const pointer bodyIn, const int bodyInLen, const pointer outPath, int out)
public void net_poll(const pointer entries, const int count, const int timeoutMs, int out)
public void net_peer_addr(const long s, int out)
public void net_peer_port(const long s, int out)
public void net_resolve_all(const pointer host, const pointer buf, const int maxCount, int out)
public void net_reverse_dns(const int addr, const pointer buf, const int cap, int out)
public void net_resolve4(const pointer host, int out)
public void str_slot_set(const pointer arr_base, const int idx, const pointer ptr, const int size)
public void str_slot_ptr(const pointer arr_base, const int idx, pointer out)
public void str_slot_size(const pointer arr_base, const int idx, int out)
public void err_print(const int code, const pointer msg)
public void suite_begin(const pointer name)
public void suite_method(const pointer name)
public void suite_case_begin(const pointer label)
public void suite_case_result(const int code, const pointer msg)
public void suite_step_fail(const pointer label, const int code, const pointer msg)
public void suite_end(const pointer name, const int total, const int failed)
