namespace fly.runtime


public void malloc(const ulong size, pointer out)
public void free(const pointer ptr)
public void realloc(const pointer ptr, const ulong size, pointer out)
public void _open(const pointer path, const int oflag, const int pmode, int out)
public void _close(const int fd, int out)
public void _read(const int fd, const pointer buf, const int count, int out)
public void _write(const int fd, const pointer buf, const int count, int out)
public void _lseeki64(const int fd, const long offset, const int origin, long out)
public void GetStdHandle(const int nStdHandle, pointer out)
public void WriteFile(const pointer h, const pointer buf, const int n, const pointer written, const pointer overlapped, int out)
public void ExitProcess(const int code)
public void CreateThread(const pointer attrs, const ulong stack, const pointer start, const pointer param, const int flags, const pointer threadId, pointer out)
public void CloseHandle(const pointer h, int out)
public void CreateProcessA(const pointer app, const pointer cmd, const pointer pa, const pointer ta, const int inherit, const int flags, const pointer env, const pointer cwd, const pointer si, const pointer pi, int out)
public void GetLastError(int out)
public void WaitForSingleObject(const pointer h, const int ms, int out)
public void GetExitCodeProcess(const pointer h, const pointer code, int out)
public void WaitOnAddress(const pointer addr, const pointer compare, const ulong size, const int ms, int out)
public void WakeByAddressSingle(const pointer addr)
public void WakeByAddressAll(const pointer addr)
public void __atomic_load_4(const pointer ptr, const int memorder, int out)
public void __atomic_store_4(const pointer ptr, const int val, const int memorder)
public void __atomic_compare_exchange_4(const pointer ptr, const pointer expected, const int desired, const int wk, const int success, const int failure, bool out)
public void __atomic_fetch_add_4(const pointer ptr, const int val, const int memorder, int out)
public void GetFileAttributesExA(const pointer path, const int level, const pointer info, int out)
public void FindFirstFileA(const pointer path, const pointer data, pointer out)
public void FindNextFileA(const pointer h, const pointer data, int out)
public void FindClose(const pointer h, int out)
public void CreateDirectoryA(const pointer path, const pointer sa, int out)
public void RemoveDirectoryA(const pointer path, int out)
public void DeleteFileA(const pointer path, int out)
public void MoveFileExA(const pointer src, const pointer dst, const int flags, int out)
public void CreateSymbolicLinkA(const pointer link, const pointer target, const int flags, int out)
public void CreateFileA(const pointer path, const int access, const int share, const pointer sa, const int disp, const int attrs, const pointer templ, pointer out)
public void SetFilePointerEx(const pointer h, const long dist, const pointer newp, const int method, int out)
public void SetEndOfFile(const pointer h, int out)
public void SetFileAttributesA(const pointer path, const int attrs, int out)
public void GetSystemTimeAsFileTime(const pointer ft)
public void QueryPerformanceCounter(const pointer cnt, int out)
public void QueryPerformanceFrequency(const pointer freq, int out)
public void Sleep(const int ms)
public void GetCurrentDirectoryA(const int n, const pointer buf, int out)
public void SetCurrentDirectoryA(const pointer path, int out)
public void GetEnvironmentVariableA(const pointer name, const pointer buf, const int n, int out)
public void SetEnvironmentVariableA(const pointer name, const pointer val, int out)
public void GetEnvironmentStringsA(pointer out)
public void FreeEnvironmentStringsA(const pointer block, int out)
public void GetComputerNameA(const pointer buf, const pointer size, int out)
public void GetVersion(int out)
public void GetModuleFileNameA(const pointer mod, const pointer buf, const int n, int out)
public void GetCommandLineA(pointer out)
public void strlen(const pointer s, ulong out)
public void erf(const double x, double out)
public void erfc(const double x, double out)
public void tgamma(const double x, double out)
public void asin(const double x, double out)
public void acos(const double x, double out)
public void atan(const double x, double out)
public void atan2(const double y, const double x, double out)
public void sinh(const double x, double out)
public void cosh(const double x, double out)
public void tanh(const double x, double out)
public void hypot(const double x, const double y, double out)
public void asinh(const double x, double out)
public void acosh(const double x, double out)
public void atanh(const double x, double out)
public void mem_alloc(const ulong size, pointer out)
public void mem_free(const pointer ptr, const ulong size)
public void mem_realloc(const pointer ptr, const ulong newSize, pointer out)
public void io_write(const int fd, const pointer buf, const ulong count, long out)
public void proc_exit(const int code)
public void fs_open(const pointer path, const int flags, const int mode, int out)
public void fs_close(const int fd)
public void fs_read(const int fd, const pointer buf, const ulong count, long out)
public void fs_write(const int fd, const pointer buf, const ulong count, long out)
public void fs_seek(const int fd, const long offset, const int whence, long out)
public void fs_size(const pointer path, long out)
public void fs_mode(const pointer path, int out)
public void fs_lsize(const pointer path, long out)
public void fs_lmode(const pointer path, int out)
public void fs_mkdir(const pointer path, const int mode, int out)
public void fs_rmdir(const pointer path, int out)
public void fs_unlink(const pointer path, int out)
public void fs_rename(const pointer src, const pointer dst, int out)
public void fs_fsync(const int fd, int out)
public void fs_truncate(const pointer path, const long size, int out)
public void fs_chmod(const pointer path, const int mode, int out)
public void fs_symlink(const pointer target, const pointer link, int out)
public void fs_readlink(const pointer path, const pointer buf, const ulong size, int out)
public void fs_getdents(const int fd, const pointer buf, const ulong size, int out)
public void dir_open(const pointer path, pointer out)
public void dir_read(const pointer ctx, const pointer buf, const ulong size, int out)
public void dir_close(const pointer ctx)
public void time_now_ns(long out)
public void time_mono_ns(long out)
public void time_sleep(const long sec, const long nsec)
public void env_chdir(const pointer path, int out)
public void env_set(const pointer key, const pointer val, int out)
public void env_delete(const pointer key, int out)
public void env_getcwd(const pointer buf, const ulong cap, int out)
public void env_get(const pointer key, const pointer buf, const ulong size, int out)
public void env_hostname(const pointer buf, const ulong size, int out)
public void env_arch(const pointer buf, const ulong size, int out)
public void env_kernel(const pointer buf, const ulong size, int out)
public void env_kernelversion(const pointer buf, const ulong size, int out)
public void env_osname(const pointer buf, const ulong size, int out)
public void env_exe_path(const pointer buf, const ulong size, int out)
public void env_all_count(int out)
public void env_all_fill(const pointer arr_base, const int count)
public void env_args_count(int out)
public void env_args_fill(const pointer arr_base, const int count)
public void env_init(const int argc, const pointer argv)
public void proc_exec(const pointer path, const pointer argv, int out)
public void thread_spawn(const pointer fn, const pointer arg, const ulong stackSize, int out)
public void futex_wait(const pointer addr, const int expected)
public void futex_wake(const pointer addr, const int count, int out)
public void atomic_load_i32(const pointer addr, int out)
public void atomic_store_i32(const pointer addr, const int val)
public void atomic_cas_i32(const pointer addr, const int expected, const int desired, int out)
public void atomic_fetch_add_i32(const pointer addr, const int delta, int out)
public void str_slot_set(const pointer arr_base, const int idx, const pointer ptr, const int size)
public void str_slot_ptr(const pointer arr_base, const int idx, pointer out)
public void str_slot_size(const pointer arr_base, const int idx, int out)
