namespace fly.runtime

public mem_alloc(const ulong size, long out)
public mem_free(const long ptr, const ulong size)
public mem_realloc(const long ptr, const ulong newSize, long out)

public io_write(const int fd, const long buf, const ulong count, long out)

public proc_exit(const int code)
public proc_exec(const long path, const long argv, int out)

public thread_spawn(const long fn, const long arg, const ulong stackSize, int out)
public futex_wait(const long addr, const int expected)
public futex_wake(const long addr, const int count, int out)

public atomic_load_i32(const long addr, int out)
public atomic_store_i32(const long addr, const int val)
public atomic_cas_i32(const long addr, const int expected, const int desired, int out)
public atomic_fetch_add_i32(const long addr, const int delta, int out)

public erf(const double x, double out)
public tgamma(const double x, double out)
public asin(const double x, double out)
public acos(const double x, double out)
public atan(const double x, double out)
public atan2(const double y, const double x, double out)
public sinh(const double x, double out)
public cosh(const double x, double out)
public tanh(const double x, double out)
public hypot(const double x, const double y, double out)
public asinh(const double x, double out)
public acosh(const double x, double out)
public atanh(const double x, double out)
public erfc(const double x, double out)

public fs_open(const long path, const int flags, const int mode, int out)
public fs_close(const int fd)
public fs_read(const int fd, const long buf, const ulong count, long out)
public fs_write(const int fd, const long buf, const ulong count, long out)
public fs_seek(const int fd, const long offset, const int whence, long out)
public fs_stat(const long path, ulong size_out, int mode_out, int out)
public fs_lstat(const long path, ulong size_out, int mode_out, int out)
public fs_size(const long path, long out)
public fs_mode(const long path, int out)
public fs_lsize(const long path, long out)
public fs_lmode(const long path, int out)
public fs_mkdir(const long path, const int mode, int out)
public fs_rmdir(const long path, int out)
public fs_unlink(const long path, int out)
public fs_rename(const long src, const long dst, int out)
public fs_fsync(const int fd, int out)
public fs_truncate(const long path, const long size, int out)
public fs_chmod(const long path, const int mode, int out)
public fs_symlink(const long target, const long link, int out)
public fs_readlink(const long path, const long buf, const ulong size, int out)
public fs_getdents(const int fd, const long buf, const ulong size, int out)

public time_realtime(long sec_out, long nsec_out, int out)
public time_monotonic(long sec_out, long nsec_out, int out)
public time_now_ns(long out)
public time_mono_ns(long out)
public time_sleep(const long sec, const long nsec)

public env_getcwd(const long buf, const ulong cap, int out)
public env_chdir(const long path, int out)
public env_get(const long key, const long buf, const ulong size, int out)
public env_set(const long key, const long val, int out)
public env_delete(const long key, int out)
public env_all_count(int out)
public env_all_get(const int idx, const long key_buf, const ulong key_size, const long val_buf, const ulong val_size)
public env_hostname(const long buf, const ulong size, int out)
public env_args_count(int out)
public env_args_get(const int idx, const long buf, const ulong size, int out)

public str_slot_set(const long arr_base, const int idx, const long ptr, const int size)
public str_slot_get(const long arr_base, const int idx, long ptr_out, int size_out)
public str_slot_ptr(const long arr_base, const int idx, long out)
public str_slot_size(const long arr_base, const int idx, int out)
public env_args_fill(const long arr_base, const int count)
public env_all_fill(const long arr_base, const int count)
public env_osname(const long buf, const ulong size, int out)
public env_arch(const long buf, const ulong size, int out)
public env_kernel(const long buf, const ulong size, int out)
public env_kernelversion(const long buf, const ulong size, int out)
public env_exe_path(const long buf, const ulong size, int out)
