namespace fly.os.path

public join(const string base, const string comp, string out)
public joinN(const string parts, const int n, string out)
public absolute(const string path, string out)
public basename(const string path, string out)
public dirname(const string path, string out)
public ext(const string path, string out)
public stem(const string path, string out)
public split(const string path, string out_dir, string out_base)
public splitExt(const string path, string out_stem, string out_ext)
public isAbsolute(const string path, bool out)
public isRelative(const string path, bool out)
public normalize(const string path, string out)
public normalizeInPlace(string path)
public rel(const string base, const string target, string out)
public isFile(const string path, bool out)
public isDir(const string path, bool out)
public isSym(const string path, bool out)
public glob(const string pattern, fly.os.env.StringArray out)
public globCount(const string pattern, int out)
public match(const string pattern, const string name, bool out)
public comp(const string path, fly.os.env.StringArray out)
public sep(byte out)
public compCount(const string path, int out)
