namespace fly.math

public struct fly_rng {
    ulong s0
    ulong s1
    ulong s2
    ulong s3
}

public long absI(const long x)
public double absF(const double x)
public int sign(const double x)
public long minI(const long a, const long b)
public double minF(const double a, const double b)
public long maxI(const long a, const long b)
public double maxF(const double a, const double b)
public long clampI(const long x, const long lo, const long hi)
public double clampF(const double x, const double lo, const double hi)
public long gcd(const long a, const long b)
public long lcm(const long a, const long b)
public divmod(const long a, const long b, long out_q, long out_r)
public double sin(const double x)
public double cos(const double x)
public double tan(const double x)
public double asin(const double x)
public double acos(const double x)
public double atan(const double x)
public double atan2(const double y, const double x)
public double sinh(const double x)
public double cosh(const double x)
public double tanh(const double x)
public double toRadians(const double x)
public double toDegrees(const double x)
public double hypot(const double a, const double b)
public double sqrt(const double x)
public double cbrt(const double x)
public double pow(const double base, const double exp)
public double exp(const double x)
public double exp2(const double x)
public double log(const double x)
public double log2(const double x)
public double log10(const double x)
public double logN(const double x, const double n)
public double floor(const double x)
public double ceil(const double x)
public double round(const double x)
public double trunc(const double x)
public double roundTo(const double x, const int n)
public bool isNaN(const double x)
public bool isInf(const double x)
public bool isFinite(const double x)
public bool approxEqual(const double a, const double b, const double epsilon)
public double copySign(const double x, const double y)
public bool isPow2(const long n)
public long nextPow2(const long n)
public int popcount(const long n)
public int leadingZeros(const long n)
public int trailingZeros(const long n)
public ulong rngNext(fly_rng rng)
public randSeed(fly_rng rng, const ulong seed)
public double randFloat(fly_rng rng)
public long randInt(fly_rng rng, const long a, const long b)
public double randNormal(fly_rng rng, const double mu, const double sigma)
public double fma(const double a, const double b, const double c)
public double lerp(const double a, const double b, const double t)
public double saturate(const double x)
public long factorialI(const int n)
public double factorialF(const int n)
public long comb(const long n, const long k)
public long perm(const long n, const long k)
public double erf(const double x)
public double erfc(const double x)
public double gamma(const double x)
public double asinh(const double x)
public double acosh(const double x)
public double atanh(const double x)
