namespace fly.str

public int len(const string src)
public bool isEmpty(const string src)
public bool equals(const string a, const string b)
public bool equalsIgnoreCase(const string a, const string b)
public bool startsWith(const string src, const string prefix)
public bool endsWith(const string src, const string suffix)
public int indexOf(const string src, const string sub)
public int lastIndexOf(const string src, const string sub)
public bool contains(const string src, const string sub)
public int count(const string src, const string sub)
public string toUpper(const string src)
public string toLower(const string src)
public string trim(const string src)
public string trimLeft(const string src)
public string trimRight(const string src)
public string substring(const string src, const int start, const int end)
public string concat(const string a, const string b)
public string repeat(const string src, const int count)
public string replace(const string src, const string from, const string to)
public string convert(const int src)
