namespace fly.llvm

public sqrt(const double x, double out)
public sin(const double x, double out)
public cos(const double x, double out)
public fabs(const double x, double out)
public floor(const double x, double out)
public ceil(const double x, double out)
public round(const double x, double out)
public trunc(const double x, double out)
public exp(const double x, double out)
public exp2(const double x, double out)
public log(const double x, double out)
public log2(const double x, double out)
public log10(const double x, double out)
public tan(const double x, double out)
public pow(const double b, const double e, double out)
public fma(const double a, const double b, const double c, double out)
public fmin(const double a, const double b, double out)
public fmax(const double a, const double b, double out)
public copysign(const double x, const double y, double out)
public sqrtf(const float x, float out)
public fabsf(const float x, float out)
public floorf(const float x, float out)
public ceilf(const float x, float out)
public ctpop(const long n, int out)
public ctlz(const long n, int out)
public cttz(const long n, int out)
public bswap(const long n, long out)
public bitreverse(const long n, long out)
public memcpy(const long dst, const long src, const ulong n)
public memmove(const long dst, const long src, const ulong n)
public memset(const long dst, const byte val, const ulong n)

// ── String struct primitives (string = { ptr, i32 size }) ──────────────────
public strSize(const string s, int out)
public strByteAt(const string s, const int i, byte out)
public strGetPtr(const string s, long out)
public strMake(const long ptr, const int size, string out)
public strPoke(const long ptr, const int i, const byte val)
public ptrByteAt(const long ptr, const int i, byte out)
public longToInt(const long v, int out)
