namespace fly.math

public struct fly_rng {
    ulong s0
    ulong s1
    ulong s2
    ulong s3
}

public absI(const long x, long out)
public absF(const double x, double out)
public sign(const double x, int out)
public minI(const long a, const long b, long out)
public minF(const double a, const double b, double out)
public maxI(const long a, const long b, long out)
public maxF(const double a, const double b, double out)
public clampI(const long x, const long lo, const long hi, long out)
public clampF(const double x, const double lo, const double hi, double out)
public gcd(const long a, const long b, long out)
public lcm(const long a, const long b, long out)
public divmod(const long a, const long b, long out_q, long out_r)
public sin(const double x, double out)
public cos(const double x, double out)
public tan(const double x, double out)
public asin(const double x, double out)
public acos(const double x, double out)
public atan(const double x, double out)
public atan2(const double y, const double x, double out)
public sinh(const double x, double out)
public cosh(const double x, double out)
public tanh(const double x, double out)
public toRadians(const double x, double out)
public toDegrees(const double x, double out)
public hypot(const double a, const double b, double out)
public sqrt(const double x, double out)
public cbrt(const double x, double out)
public pow(const double base, const double exp, double out)
public exp(const double x, double out)
public exp2(const double x, double out)
public log(const double x, double out)
public log2(const double x, double out)
public log10(const double x, double out)
public logN(const double x, const double n, double out)
public floor(const double x, double out)
public ceil(const double x, double out)
public round(const double x, double out)
public trunc(const double x, double out)
public roundTo(const double x, const int n, double out)
public isNaN(const double x, bool out)
public isInf(const double x, bool out)
public isFinite(const double x, bool out)
public approxEqual(const double a, const double b, const double epsilon, bool out)
public copySign(const double x, const double y, double out)
public isPow2(const long n, bool out)
public nextPow2(const long n, long out)
public popcount(const long n, int out)
public leadingZeros(const long n, int out)
public trailingZeros(const long n, int out)
public rngNext(fly_rng rng, ulong out)
public randSeed(fly_rng rng, const ulong seed)
public randFloat(fly_rng rng, double out)
public randInt(fly_rng rng, const long a, const long b, long out)
public randNormal(fly_rng rng, const double mu, const double sigma, double out)
public fma(const double a, const double b, const double c, double out)
public lerp(const double a, const double b, const double t, double out)
public saturate(const double x, double out)
public factorialI(const int n, long out)
public factorialF(const int n, double out)
public comb(const long n, const long k, long out)
public perm(const long n, const long k, long out)
public erf(const double x, double out)
public gamma(const double x, double out)
