namespace fly.str

public convert(const int src, string out)
public len(const string src, int out)
public isEmpty(const string src, bool out)
public contains(const string src, const string sub, bool out)
public startsWith(const string src, const string prefix, bool out)
public endsWith(const string src, const string suffix, bool out)
public indexOf(const string src, const string sub, int out)
public lastIndexOf(const string src, const string sub, int out)
public equals(const string a, const string b, bool out)
public equalsIgnoreCase(const string a, const string b, bool out)
public count(const string src, const string sub, int out)
public toUpper(const string src, string out)
public toLower(const string src, string out)
public trim(const string src, string out)
public trimLeft(const string src, string out)
public trimRight(const string src, string out)
public substring(const string src, const int start, const int end, string out)
public replace(const string src, const string from, const string to, string out)
public repeat(const string src, const int count, string out)
public concat(const string a, const string b, string out)
