//===--------------------------------------------------------------------------------------------------------------===//
// include/Basic/DiagnosticAnalysisKinds.inc
//
// Part of the Fly Project https://flylang.org
// Under the Apache License v2.0 see LICENSE for details.
// Thank you to LLVM Project https://llvm.org/
//
//===--------------------------------------------------------------------------------------------------------------===//


#ifdef ANALYSISSTART
__ANALYSISSTART = DIAG_START_ANALYSIS,
#undef ANALYSISSTART
#endif

