name: Build

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request
  push:
    paths-ignore:
      - "**.md"
  pull_request:
    paths-ignore:
      - "**.md"

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release
  BUILD_DIR: build
  LLVM_VERSION: 11.1.0
  WIN_FILE: win-x64.zip
  MACOS_FILE: macos-x86_64.tar.gz
  LINUX_FILE: linux-x86_64.tar.gz

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:

  # This workflow contains multiple "build" jobs
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-latest, macos-latest, windows-latest ]
    runs-on: ${{ matrix.os }}

    outputs:
      winversion: ${{ steps.version-win.outputs.version }}
      version: ${{ steps.version.outputs.version }}

    steps:
      - uses: actions/checkout@v2

      - name: Configure
        # Some projects don't allow in-source building, so create a separate build directory
        # We'll use this as our working directory for all subsequent commands
        run: cmake -E make_directory ${{env.BUILD_DIR}}

      - name: Build
        working-directory: ${{github.workspace}}/${{env.BUILD_DIR}}
        # Some projects don't allow in-source building, so create a separate build directory
        # We'll use this as our working directory for all subsequent commands
        run: |
          cmake .. -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} -DCMAKE_VERBOSE_MAKEFILE=ON
          cmake --build . --config ${{env.BUILD_TYPE}}

      - name: Test
        working-directory: ${{github.workspace}}/${{env.BUILD_DIR}}
        # Execute tests defined by the CMake configuration.
        # See https://cmake.org/cmake/help/latest/manual/ctest.1.html for more detail
        run: ctest -C ${{env.BUILD_TYPE}} --rerun-failed --output-on-failure --gmock_verbose=info --gtest_stack_trace_depth=10

      - name: Read Version (Unix)
        id: version
        if: github.ref == 'refs/heads/main' && (matrix.os == 'ubuntu-latest' || matrix.os == 'macos-latest')
        run: echo "::set-output name=version::$(${{github.workspace}}/${{env.BUILD_DIR}}/src/fly --version-short)"

      - name: Read Version (Windows)
        id: version-win
        if: github.ref == 'refs/heads/main' && matrix.os == 'windows-latest'
        working-directory: ${{github.workspace}}\${{env.BUILD_DIR}}\src\${{env.BUILD_TYPE}}
        run: |
          echo "::set-output name=version::$(.\fly.exe --version-short)"

      - name: Linux Packaging
        if: github.ref == 'refs/heads/main' && matrix.os == 'ubuntu-latest'
        working-directory: ${{github.workspace}}/${{env.BUILD_DIR}}/src
        run: tar -czvf ../fly-${{ steps.version.outputs.version }}-${{env.LINUX_FILE}} fly

      - name: Windows Packaging
        if: github.ref == 'refs/heads/main' && matrix.os == 'windows-latest'
        working-directory: ${{github.workspace}}\${{env.BUILD_DIR}}\src\${{env.BUILD_TYPE}}
        run: 7z a ..\..\fly-${{ steps.version-win.outputs.version }}-${{env.WIN_FILE}} fly.exe

      - name: macOS Packaging
        if: github.ref == 'refs/heads/main' && matrix.os == 'macos-latest'
        working-directory: ${{github.workspace}}/${{env.BUILD_DIR}}/src
        run: tar -czvf ../fly-${{ steps.version.outputs.version }}-${{env.MACOS_FILE}} fly

      - uses: actions/upload-artifact@v2
        if: github.ref == 'refs/heads/main' && matrix.os == 'ubuntu-latest'
        with:
          name: linux-artifact
          path: ${{github.workspace}}/${{env.BUILD_DIR}}/fly-${{ steps.version.outputs.version }}-${{env.LINUX_FILE}}

      - uses: actions/upload-artifact@v2
        if: github.ref == 'refs/heads/main' && matrix.os == 'windows-latest'
        with:
          name: windows-artifact
          path: ${{github.workspace}}/${{env.BUILD_DIR}}/fly-${{ steps.version-win.outputs.version }}-${{env.WIN_FILE}}

      - uses: actions/upload-artifact@v2
        if: github.ref == 'refs/heads/main' && matrix.os == 'macos-latest'
        with:
          name: macos-artifact
          path: ${{github.workspace}}/${{env.BUILD_DIR}}/fly-${{ steps.version.outputs.version }}-${{env.MACOS_FILE}}

  release:
    needs: [build]
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    defaults:
      run:
        shell: bash

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: actions/download-artifact@v2
        if: github.ref == 'refs/heads/main'
        with:
          name: linux-artifact

      - uses: actions/download-artifact@v2
        if: github.ref == 'refs/heads/main'
        with:
          name: windows-artifact

      - uses: actions/download-artifact@v2
        if: github.ref == 'refs/heads/main'
        with:
          name: macos-artifact

      - name: Release
        if: github.ref == 'refs/heads/main'
        uses: actions/create-release@v1
        id: create_release
        with:
          draft: false
          prerelease: true
          release_name: Fly ${{ needs.build.outputs.version }}
          tag_name: v${{ needs.build.outputs.version }}
        env:
          GITHUB_TOKEN: ${{ github.token }}

      - name: Linux Upload
        if: github.ref == 'refs/heads/main'
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: fly-${{ needs.build.outputs.version }}-${{env.LINUX_FILE}}
          asset_name: fly-${{ needs.build.outputs.version }}-${{env.LINUX_FILE}}
          asset_content_type: application/gzip

      - name: Windows Upload
        if: github.ref == 'refs/heads/main'
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: fly-${{ needs.build.outputs.version }}-${{env.WIN_FILE}}
          asset_name: fly-${{ needs.build.outputs.version }}-${{env.WIN_FILE}}
          asset_content_type: application/gzip

      - name: macOS Upload
        if: github.ref == 'refs/heads/main'
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: fly-${{ needs.build.outputs.version }}-${{env.MACOS_FILE}}
          asset_name: fly-${{ needs.build.outputs.version }}-${{env.MACOS_FILE}}
          asset_content_type: application/gzip
