# This is a basic workflow to help you get started with Actions

name: Release

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release
  BUILD_DIR: build
  WIN_FILE: win-x64.zip
  MACOS_FILE: macos-x86_64.tar.gz
  LINUX_FILE: linux-x86_64.tar.gz

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:

  # This workflow contains multiple "build" jobs
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-latest, macos-latest, windows-latest ]
    runs-on: ${{ matrix.os }}

    outputs:
      winversion: ${{ steps.version-win.outputs.version }}
      unixversion: ${{ steps.version-unix.outputs.version }}

    steps:
      - uses: actions/checkout@v2

      - name: Create Build Environment
        # Some projects don't allow in-source building, so create a separate build directory
        # We'll use this as our working directory for all subsequent commands
        run: |
          cmake -E make_directory llvm
          cmake -E make_directory ${{env.BUILD_DIR}}

      - name: Download LLVM (Linux Release)
        if: matrix.os == 'ubuntu-latest'
        working-directory: ${{github.workspace}}/llvm
        run: |
          wget -q https://github.com/fly-lang/llvm-project/releases/download/v11.1.0-linux-x86_64/llvm-11.1.0-x86_64-linux-gnu.tar.gz
          tar -zxvf *.tar.gz

      - name: Download LLVM (macOS Release)
        if: matrix.os == 'macos-latest'
        working-directory: ${{github.workspace}}/llvm
        run: |
          wget -q https://github.com/fly-lang/llvm-project/releases/download/v11.1.0-macos-x86_64/llvm-11.1.0-x86_64-apple-darwin.tar.gz
          tar -zxvf *.tar.gz

      - name: Download LLVM (Windows Release)
        if: matrix.os == 'windows-latest'
        working-directory: ${{github.workspace}}/llvm
        shell: pwsh
        run: |
          Invoke-WebRequest -Uri https://github.com/fly-lang/llvm-project/releases/download/v11.1.0-win-x64/llvm-11.1.0-win-x64.zip -OutFile llvm.zip
          7z x *.zip

      - name: Configure & Build
        working-directory: ${{github.workspace}}/${{env.BUILD_DIR}}
        # Some projects don't allow in-source building, so create a separate build directory
        # We'll use this as our working directory for all subsequent commands
        run: |
          cmake .. -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} -DCMAKE_VERBOSE_MAKEFILE=ON -DLLVM_INSTALL_PATH=${{github.workspace}}/llvm/lib/cmake
          cmake --build . --config ${{env.BUILD_TYPE}}

      - name: Test
        working-directory: ${{github.workspace}}/${{env.BUILD_DIR}}
        # Execute tests defined by the CMake configuration.
        # See https://cmake.org/cmake/help/latest/manual/ctest.1.html for more detail
        run: ctest -C ${{env.BUILD_TYPE}} --rerun-failed --output-on-failure

      - name: Read Version (Linux)
        id: version-unix
        if: matrix.os == 'ubuntu-latest' || matrix.os == 'macos-latest'
        run: echo "::set-output name=version::$(${{github.workspace}}/${{env.BUILD_DIR}}/src/fly --version-short)"

      - name: Read Version (Windows)
        id: version-win
        if: matrix.os == 'windows-latest'
        working-directory: ${{github.workspace}}\${{env.BUILD_DIR}}\src\${{env.BUILD_TYPE}}
        run: |
          echo "::set-output name=version::$(.\fly.exe --version-short)"

      - name: Linux Packaging
        if: matrix.os == 'ubuntu-latest'
        working-directory: ${{github.workspace}}/${{env.BUILD_DIR}}/src
        run: tar -czvf ../fly-${{ steps.version-unix.outputs.version }}-${{env.LINUX_FILE}} fly

      - name: Windows Packaging
        if: matrix.os == 'windows-latest'
        working-directory: ${{github.workspace}}\${{env.BUILD_DIR}}\src\${{env.BUILD_TYPE}}
        run: 7z a ..\..\llvm-${{ steps.version-win.outputs.version }}-${{env.WIN_FILE}} fly.exe

      - name: macOS Packaging
        if: matrix.os == 'macos-latest'
        working-directory: ${{github.workspace}}/${{env.BUILD_DIR}}/src
        run: tar -czvf ../fly-${{ steps.version-unix.outputs.version }}-${{env.MACOS_FILE}} fly

      - uses: actions/upload-artifact@v2
        if: matrix.os == 'ubuntu-latest'
        with:
          name: linux-artifact
          path: ${{github.workspace}}/${{env.BUILD_DIR}}/fly-${{ steps.version-unix.outputs.version }}-${{env.LINUX_FILE}}

      - uses: actions/upload-artifact@v2
        if: matrix.os == 'windows-latest'
        with:
          name: windows-artifact
          path: ${{github.workspace}}/${{env.BUILD_DIR}}/fly-${{ steps.version-win.outputs.version }}-${{env.WIN_FILE}}

      - uses: actions/upload-artifact@v2
        if: matrix.os == 'macos-latest'
        with:
          name: macos-artifact
          path: ${{github.workspace}}/${{env.BUILD_DIR}}/fly-${{ steps.version-unix.outputs.version }}-${{env.MACOS_FILE}}

  release:
    needs: [build]
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    defaults:
      run:
        shell: bash

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Release
        uses: actions/create-release@v1
        id: create_release
        with:
          draft: false
          prerelease: true
          release_name: Fly ${{env.FLY_VERSION}} Pre-release
          tag_name: v${{env.FLY_VERSION}}
        env:
          GITHUB_TOKEN: ${{ github.token }}

      - uses: actions/download-artifact@v2
        if: matrix.os == 'ubuntu-latest'
        with:
          name: linux-artifact

      - uses: actions/download-artifact@v2
        if: matrix.os == 'windows-latest'
        with:
          name: windows-artifact

      - uses: actions/download-artifact@v2
        if: matrix.os == 'macos-latest'
        with:
          name: macos-artifact

      - name: Linux Upload
        uses: actions/upload-release-asset@v1
        if: matrix.os == 'ubuntu-latest'
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: fly-${{ needs.build.outputs.version }}-${{env.LINUX_FILE}}
          asset_name: fly-${{ needs.build.outputs.version }}-${{env.LINUX_FILE}}
          asset_content_type: application/gzip

      - name: Windows Upload
        uses: actions/upload-release-asset@v1
        if: matrix.os == 'windows-latest'
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: fly-${{ needs.build.outputs.version }}-${{env.WIN_FILE}}
          asset_name: fly-${{ needs.build.outputs.version }}-${{env.WIN_FILE}}
          asset_content_type: application/gzip

      - name: macOS Upload
        uses: actions/upload-release-asset@v1
        if: matrix.os == 'macos-latest'
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: fly-${{ needs.build.outputs.version }}-${{env.MACOS_FILE}}
          asset_name: fly-${{ needs.build.outputs.version }}-${{env.MACOS_FILE}}
          asset_content_type: application/gzip
