# This is a basic workflow to help you get started with Actions

name: Release

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release
  BUILD_PATH: ${{github.workspace}}/build

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:

  # This workflow contains multiple "build" jobs
  build:

    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os:
          - windows
          - ubuntu-latest

    defaults:
      run:
        shell: bash

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
        with:
          fetch-depth: 1

      - name: Install LLVM
        if: startsWith(matrix.os, 'linux')
        run: |
          chmod 777 ./.github/scripts/apt-install-llvm.sh
          sudo ./.github/scripts/apt-install-llvm.sh

      - name: Create Build Environment
        # Use this as our working directory for all subsequent commands
        run: cmake -E make_directory $BUILD_PATH

      - name: Download LLVM sources
        if: startsWith(matrix.os, 'windows')
        shell: pwsh
        run: |
          Invoke-WebRequest -Uri 'https://github.com/llvm/llvm-project/releases/download/llvmorg-11.1.0/llvm-11.1.0.src.tar.xz' -Out llvm-11.1.0.src.tar.xz
          7z e llvm-11.1.0.src.tar.xz
          7z x llvm-11.1.0.src.tar
          mv -f llvm-11.1.0.src $BUILD_PATH\llvm

      - name: Configure CMake
        if: startsWith(matrix.os, 'linux')
        working-directory: ${{env.BUILD_PATH}}
        run: cmake $GITHUB_WORKSPACE -DCMAKE_BUILD_TYPE=$BUILD_TYPE

      - name: Configure CMake
        if: startsWith(matrix.os, 'windows')
        working-directory: ${{env.BUILD_PATH}}
        run: cmake $GITHUB_WORKSPACE -DCMAKE_BUILD_TYPE=$BUILD_TYPE -DUSE_INSTALLED_LLVM=false

      - name: Build
        working-directory: ${{env.BUILD_PATH}}
        # Execute the build.  You can specify a specific target with "--target <NAME>"
        run: cmake --build . --config $BUILD_TYPE

      - name: Test
        working-directory: ${{env.BUILD_PATH}}
        # Execute tests defined by the CMake configuration.
        # See https://cmake.org/cmake/help/latest/manual/ctest.1.html for more detail
        run: ctest -C $BUILD_TYPE

      - name: Read Version
        id: version
        run: echo "::set-output name=version::$(./src/fly --version-short)"
        working-directory: ${{env.BUILD_PATH}}

      - name: Packaging
        if: startsWith(matrix.os, 'linux')
        working-directory: ${{env.BUILD_PATH}}/src
        run: tar -czvf ../fly-${{ steps.version.outputs.version }}-linux-x86_64.tar.gz fly
        
      - uses: actions/upload-artifact@v2
        if: startsWith(matrix.os, 'linux')
        with:
          name: linux-artifact
          path: ${{env.BUILD_PATH}}/fly-${{ steps.version.outputs.version }}-linux-x86_64.tar.gz

      - name: Packaging
        if: startsWith(matrix.os, 'windows')
        working-directory: ${{env.BUILD_PATH}}
        run: zip fly-${{ steps.version.outputs.version }}-win-x64 ./src/fly

      - uses: actions/upload-artifact@v2
        if: startsWith(matrix.os, 'windows')
        with:
          name: windows-artifact
          path: ${{env.BUILD_PATH}}/fly-${{ steps.version.outputs.version }}-win-x64.zip

  release:
    needs: build
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    defaults:
      run:
        shell: bash

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Release
        uses: actions/create-release@v1
        id: create_release
        with:
          draft: false
          prerelease: true
          release_name: Fly ${{env.FLY_VERSION}} Pre-release
          tag_name: v${{env.FLY_VERSION}}
        env:
          GITHUB_TOKEN: ${{ github.token }}

      - uses: actions/download-artifact@v2
        with:
          name: linux-artifact

      - name: Linux Upload
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: fly-${{ steps.version.outputs.version }}-linux-x86_64.tar.gz
          asset_name: fly-${{ steps.version.outputs.version }}-linux-x86_64.tar.gz
          asset_content_type: application/gzip

      - uses: actions/download-artifact@v2
        with:
          name: windows-artifact

      - name: Windows Upload
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ${{env.BUILD_PATH}}/fly-${{ steps.version.outputs.version }}-win-x64.zip
          asset_name: fly-${{ steps.version.outputs.version }}-win-x64.zip
          asset_content_type: application/zip
