namespace fly.os.path

public string join(const string base, const string comp)
public string joinN(const string parts, const int n)
public string absolute(const string path)
public string basename(const string path)
public string dirname(const string path)
public string ext(const string path)
public string stem(const string path)
public split(const string path)
public splitExt(const string path)
public bool isAbsolute(const string path)
public bool isRelative(const string path)
public string normalize(const string path)
public normalizeInPlace(string path)
public string rel(const string base, const string target)
public bool isFile(const string path)
public bool isDir(const string path)
public bool isSym(const string path)
public fly.os.env.StringArray glob(const string pattern)
public int globCount(const string pattern)
public bool match(const string pattern, const string name)
public fly.os.env.StringArray comp(const string path)
public byte sep()
public int compCount(const string path)
